// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/pb/chat.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A chat message as delivered to subscribers.
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A server-assigned unique identifier for the message (opaque string).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room name / identifier the message belongs to.
	Room string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	// Sender's identifier (username, client id, etc.).
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	// Message body / payload.
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Server-assigned timestamp for when the message was accepted.
	Ts            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_internal_pb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_internal_pb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// Request from client to send a message to a room.
// The server will typically assign the resulting message ID and timestamp.
type SendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room to send the message to.
	Room string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// Sender's identifier.
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Message body.
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_internal_pb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *SendRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Response from server after processing SendRequest.
type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the send was accepted.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// If ok, the assigned message id.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// If ok, the server timestamp for the message.
	Ts *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// Optional error string when ok == false.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_internal_pb_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendResponse) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *SendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to subscribe / notify stream for a room.
// The server will stream ChatMessage messages for the requested room.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room to subscribe to.
	Room string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// Optional: Ask for messages after this message id (exclusive).
	// If empty, the server will stream only new messages from subscription time.
	SinceId string `protobuf:"bytes,2,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	// Optional: Ask for messages after this timestamp (exclusive).
	// If omitted and since_id is empty, subscription starts from now.
	Since         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_pb_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *SubscribeRequest) GetSinceId() string {
	if x != nil {
		return x.SinceId
	}
	return ""
}

func (x *SubscribeRequest) GetSince() *timestamp.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

var File_internal_pb_chat_proto protoreflect.FileDescriptor

const file_internal_pb_chat_proto_rawDesc = "" +
	"\n" +
	"\x16internal/pb/chat.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12*\n" +
	"\x02ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"M\n" +
	"\vSendRequest\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"p\n" +
	"\fSendResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"s\n" +
	"\x10SubscribeRequest\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x19\n" +
	"\bsince_id\x18\x02 \x01(\tR\asinceId\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since2s\n" +
	"\vChatService\x12-\n" +
	"\x04Send\x12\x11.chat.SendRequest\x1a\x12.chat.SendResponse\x125\n" +
	"\x06Notify\x12\x16.chat.SubscribeRequest\x1a\x11.chat.ChatMessage0\x01B@Z>github.com/bersen66/software_design_course/chat/internal/pb;pbb\x06proto3"

var (
	file_internal_pb_chat_proto_rawDescOnce sync.Once
	file_internal_pb_chat_proto_rawDescData []byte
)

func file_internal_pb_chat_proto_rawDescGZIP() []byte {
	file_internal_pb_chat_proto_rawDescOnce.Do(func() {
		file_internal_pb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_chat_proto_rawDesc), len(file_internal_pb_chat_proto_rawDesc)))
	})
	return file_internal_pb_chat_proto_rawDescData
}

var file_internal_pb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_chat_proto_goTypes = []any{
	(*ChatMessage)(nil),         // 0: chat.ChatMessage
	(*SendRequest)(nil),         // 1: chat.SendRequest
	(*SendResponse)(nil),        // 2: chat.SendResponse
	(*SubscribeRequest)(nil),    // 3: chat.SubscribeRequest
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_internal_pb_chat_proto_depIdxs = []int32{
	4, // 0: chat.ChatMessage.ts:type_name -> google.protobuf.Timestamp
	4, // 1: chat.SendResponse.ts:type_name -> google.protobuf.Timestamp
	4, // 2: chat.SubscribeRequest.since:type_name -> google.protobuf.Timestamp
	1, // 3: chat.ChatService.Send:input_type -> chat.SendRequest
	3, // 4: chat.ChatService.Notify:input_type -> chat.SubscribeRequest
	2, // 5: chat.ChatService.Send:output_type -> chat.SendResponse
	0, // 6: chat.ChatService.Notify:output_type -> chat.ChatMessage
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_pb_chat_proto_init() }
func file_internal_pb_chat_proto_init() {
	if File_internal_pb_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_chat_proto_rawDesc), len(file_internal_pb_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_chat_proto_goTypes,
		DependencyIndexes: file_internal_pb_chat_proto_depIdxs,
		MessageInfos:      file_internal_pb_chat_proto_msgTypes,
	}.Build()
	File_internal_pb_chat_proto = out.File
	file_internal_pb_chat_proto_goTypes = nil
	file_internal_pb_chat_proto_depIdxs = nil
}
